<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Product;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('products')->insert([
        ['title'=> 'WATERDOG DOME 3' ,
        'pricing'=> 68.38,
        'short_description'=> 'Carpa Iglu Dome 3 Para 4 Personas Waterdog Camping Ml Full ' ,
        'long_description'=> 'Los tejidos empleados por WATERDOG evitan la condensación de la transpiración corporal. Costuras termoselladas de fabrica para asegurar que no se agrieten. Aleros de poliester que no se hunden ni se embolsan en climas húmedos. Costuras reforzadas termoselladas. Mosquitero: Poly Mesh No See Um. Cierres ZHZ reforzados. Varillas Fibra de Vidrio 8.5 mm. Cubretecho hasta el piso con Proteccion U.V. Piso: Polietileno 100% PE SHEET 12X10 130 G/M2. Tejido Exterior: Poliéster 68D/190T PU (con recubrimiento interior silver). Bolso con correa de transporte. ',
        'category_id'=> 2,
        'created_at' => date("Y-m-d H:i:s"),
        'updated_at' => date("Y-m-d H:i:s")],
        ['title'=> 'Natway Blac 30',
        'pricing'=> 56.15,
        'short_description'=> 'Mochila trekking Natway Blanc 30 litros con cubremochila impermeable ',
        'long_description'=> 'Mochila de ataque de gran capacidad ideal para trekking, carreras de aventura, escalada Comodo espaldar con mesh respirable. Agarre de pecho Agarre lumbar con bolsillo riñonera Sistema AIR SYSTEM de excelente respirabilidad. Sistema de respaldo super liviano. Tiras de hombro acolchadas, tira de cintura y arnés de esternón para ajuste preciso. Cinturón de mesh respirable. Bolsillos frontal y bolsillo con tapa para indumentaria y accesorios. Bolsillo laterales extensibles con tela poly jersey. Puntos de ajuste para bastones de trekking, luces, etc. Cubre mochila en bolsillo inferior. ',
        'category_id'=> 3,
        'created_at' => date("Y-m-d H:i:s"),
        'updated_at' => date("Y-m-d H:i:s")],
        ['title'=> 'Botas Borcegos Hi Tec' ,
        'pricing'=> 99.00,
        'short_description'=> 'Botas Borcegos Hi Tec Impermeable Hombre Montaña Trekking ',
        'long_description'=> 'Bota de trekking robusta, impermeable y respirable gracias a su membrana Dri-Tec. Su suela Vibram, brinda una excelente adherencia en cualquier terreno y su relleno de Thinsulate proporciona abrigo incluso en condiciones invernales en senderos de trekking. Corte de piel hidrófuga. Membrana impermeable y transpirable Dri-Tec. Tratamiento i-shield, repele el agua, el aceite y protege al calzado de las manchas. 200 gramos de Tinsulate. Material sintético que retiene el calor dentro de la bota. Plantilla recambiable Ortholite. Entresuela de EVA moldeada. Suela Vibram. ',
        'category_id'=> 1,
        'created_at' => date("Y-m-d H:i:s"),
        'updated_at' => date("Y-m-d H:i:s")],
        ['title'=> 'WATERDOG TA450D',
        'pricing'=> 18.20,
        'short_description'=> 'Botella Termica Deportiva Waterdog 450 Cc Cantimplora Termo',
        'long_description'=> 'Construida con dos paredes de Acero Inoxidable que generan un aislamiento al vacío para lograr mantener el agua fría o caliente por más tiempo. Botella fácil de llenar y de poner hielo gracias a su boca ancha. Posee filtro de Té o Café que se puede utilizar de forma directa. La tapa posee correa para un fácil transporte. Aprobados por INTI e INAL (no tóxicos). 100% acero inoxidable. Fácil de llenar, gracias a su boca ancha. Se abre y se cierra presionando a rosca. Incluye filtro para té o café que se puede emplear colocándolo en forma directa. Compacto por fuera, con una gran capacidad interior. Capacidad: 450 cc. ',
        'category_id'=> 4,
        'created_at' => date("Y-m-d H:i:s"),
        'updated_at' => date("Y-m-d H:i:s")],
        ['title'=> 'Hi-Tec Tortola Escape',
        'pricing'=> 52.00,
        'short_description'=> 'Sandalia multideporte desarrollada para brindar frescura y comodidad en la temporada estival.',
        'long_description'=>'Un concepto hibrido que auna elementos tecnicos del calzado outdoor y el diseño funcional de las sandalias para adaptarse perfectamente a escenarios en la naturaleza o la ciudad. Los agujeros de ventilacion y drenaje en el corte, asi como los materiales empleados en su fabricacion mantienen el pie muy ventilado, favoreciendo la transpiracion. El confort tambien esta garantizado por la suavidad que aporta el forro interior de neopreno que evita roces y ampollas. Además, esta sandalia es fácil de calzar y de ajustar al pie por su sistema de lazado simple. Su lengüeta acolchada y los refuerzos de caucho en puntera y talón protegen de lesiones que pueden dificultar nuestra marcha. La plantilla extraíble aporta comodidad al andar y la suela de caucho carbono permite el uso regular de este modelo por terrenos de fácil recorrido. Corte de nobuck sintético Forro de neopreno Sistema de lazado con cordón elástico ',
        'category_id'=> 1,
        'created_at' => date("Y-m-d H:i:s"),
        'updated_at' => date("Y-m-d H:i:s")],
        ['title'=> 'WATERDOG DOME 3' ,
        'pricing'=> 68.38,
        'short_description'=> 'Carpa Iglu Dome 3 Para 4 Personas Waterdog Camping Ml Full ' ,
        'long_description'=> 'Los tejidos empleados por WATERDOG evitan la condensación de la transpiración corporal. Costuras termoselladas de fabrica para asegurar que no se agrieten. Aleros de poliester que no se hunden ni se embolsan en climas húmedos. Costuras reforzadas termoselladas. Mosquitero: Poly Mesh No See Um. Cierres ZHZ reforzados. Varillas Fibra de Vidrio 8.5 mm. Cubretecho hasta el piso con Proteccion U.V. Piso: Polietileno 100% PE SHEET 12X10 130 G/M2. Tejido Exterior: Poliéster 68D/190T PU (con recubrimiento interior silver). Bolso con correa de transporte. ',
        'category_id'=> 2,
        'created_at' => date("Y-m-d H:i:s"),
        'updated_at' => date("Y-m-d H:i:s")],
        ['title'=> 'Natway Blac 30',
        'pricing'=> 56.15,
        'short_description'=> 'Mochila trekking Natway Blanc 30 litros con cubremochila impermeable ',
        'long_description'=> 'Mochila de ataque de gran capacidad ideal para trekking, carreras de aventura, escalada Comodo espaldar con mesh respirable. Agarre de pecho Agarre lumbar con bolsillo riñonera Sistema AIR SYSTEM de excelente respirabilidad. Sistema de respaldo super liviano. Tiras de hombro acolchadas, tira de cintura y arnés de esternón para ajuste preciso. Cinturón de mesh respirable. Bolsillos frontal y bolsillo con tapa para indumentaria y accesorios. Bolsillo laterales extensibles con tela poly jersey. Puntos de ajuste para bastones de trekking, luces, etc. Cubre mochila en bolsillo inferior. ',
        'category_id'=> 3,
        'created_at' => date("Y-m-d H:i:s"),
        'updated_at' => date("Y-m-d H:i:s")],
        ['title'=> 'Botas Borcegos Hi Tec' ,
        'pricing'=> 99.00,
        'short_description'=> 'Botas Borcegos Hi Tec Impermeable Hombre Montaña Trekking ',
        'long_description'=> 'Bota de trekking robusta, impermeable y respirable gracias a su membrana Dri-Tec. Su suela Vibram, brinda una excelente adherencia en cualquier terreno y su relleno de Thinsulate proporciona abrigo incluso en condiciones invernales en senderos de trekking. Corte de piel hidrófuga. Membrana impermeable y transpirable Dri-Tec. Tratamiento i-shield, repele el agua, el aceite y protege al calzado de las manchas. 200 gramos de Tinsulate. Material sintético que retiene el calor dentro de la bota. Plantilla recambiable Ortholite. Entresuela de EVA moldeada. Suela Vibram. ',
        'category_id'=> 1,
        'created_at' => date("Y-m-d H:i:s"),
        'updated_at' => date("Y-m-d H:i:s")],
        ['title'=> 'WATERDOG TA450D',
        'pricing'=> 18.20,
        'short_description'=> 'Botella Termica Deportiva Waterdog 450 Cc Cantimplora Termo',
        'long_description'=> 'Construida con dos paredes de Acero Inoxidable que generan un aislamiento al vacío para lograr mantener el agua fría o caliente por más tiempo. Botella fácil de llenar y de poner hielo gracias a su boca ancha. Posee filtro de Té o Café que se puede utilizar de forma directa. La tapa posee correa para un fácil transporte. Aprobados por INTI e INAL (no tóxicos). 100% acero inoxidable. Fácil de llenar, gracias a su boca ancha. Se abre y se cierra presionando a rosca. Incluye filtro para té o café que se puede emplear colocándolo en forma directa. Compacto por fuera, con una gran capacidad interior. Capacidad: 450 cc. ',
        'category_id'=> 4,
        'created_at' => date("Y-m-d H:i:s"),
        'updated_at' => date("Y-m-d H:i:s")],
        ['title'=> 'Hi-Tec Tortola Escape',
        'pricing'=> 52.00,
        'short_description'=> 'Sandalia multideporte desarrollada para brindar frescura y comodidad en la temporada estival.',
        'long_description'=>'Un concepto hibrido que auna elementos tecnicos del calzado outdoor y el diseño funcional de las sandalias para adaptarse perfectamente a escenarios en la naturaleza o la ciudad. Los agujeros de ventilacion y drenaje en el corte, asi como los materiales empleados en su fabricacion mantienen el pie muy ventilado, favoreciendo la transpiracion. El confort tambien esta garantizado por la suavidad que aporta el forro interior de neopreno que evita roces y ampollas. Además, esta sandalia es fácil de calzar y de ajustar al pie por su sistema de lazado simple. Su lengüeta acolchada y los refuerzos de caucho en puntera y talón protegen de lesiones que pueden dificultar nuestra marcha. La plantilla extraíble aporta comodidad al andar y la suela de caucho carbono permite el uso regular de este modelo por terrenos de fácil recorrido. Corte de nobuck sintético Forro de neopreno Sistema de lazado con cordón elástico ',
        'category_id'=> 1,
        'created_at' => date("Y-m-d H:i:s"),
        'updated_at' => date("Y-m-d H:i:s")],
        ['title'=> 'WATERDOG DOME 3' ,
        'pricing'=> 68.38,
        'short_description'=> 'Carpa Iglu Dome 3 Para 4 Personas Waterdog Camping Ml Full ' ,
        'long_description'=> 'Los tejidos empleados por WATERDOG evitan la condensación de la transpiración corporal. Costuras termoselladas de fabrica para asegurar que no se agrieten. Aleros de poliester que no se hunden ni se embolsan en climas húmedos. Costuras reforzadas termoselladas. Mosquitero: Poly Mesh No See Um. Cierres ZHZ reforzados. Varillas Fibra de Vidrio 8.5 mm. Cubretecho hasta el piso con Proteccion U.V. Piso: Polietileno 100% PE SHEET 12X10 130 G/M2. Tejido Exterior: Poliéster 68D/190T PU (con recubrimiento interior silver). Bolso con correa de transporte. ',
        'category_id'=> 2,
        'created_at' => date("Y-m-d H:i:s"),
        'updated_at' => date("Y-m-d H:i:s")],
        ['title'=> 'Natway Blac 30',
        'pricing'=> 56.15,
        'short_description'=> 'Mochila trekking Natway Blanc 30 litros con cubremochila impermeable ',
        'long_description'=> 'Mochila de ataque de gran capacidad ideal para trekking, carreras de aventura, escalada Comodo espaldar con mesh respirable. Agarre de pecho Agarre lumbar con bolsillo riñonera Sistema AIR SYSTEM de excelente respirabilidad. Sistema de respaldo super liviano. Tiras de hombro acolchadas, tira de cintura y arnés de esternón para ajuste preciso. Cinturón de mesh respirable. Bolsillos frontal y bolsillo con tapa para indumentaria y accesorios. Bolsillo laterales extensibles con tela poly jersey. Puntos de ajuste para bastones de trekking, luces, etc. Cubre mochila en bolsillo inferior. ',
        'category_id'=> 3,
        'created_at' => date("Y-m-d H:i:s"),
        'updated_at' => date("Y-m-d H:i:s")],
        ['title'=> 'Botas Borcegos Hi Tec' ,
        'pricing'=> 99.00,
        'short_description'=> 'Botas Borcegos Hi Tec Impermeable Hombre Montaña Trekking ',
        'long_description'=> 'Bota de trekking robusta, impermeable y respirable gracias a su membrana Dri-Tec. Su suela Vibram, brinda una excelente adherencia en cualquier terreno y su relleno de Thinsulate proporciona abrigo incluso en condiciones invernales en senderos de trekking. Corte de piel hidrófuga. Membrana impermeable y transpirable Dri-Tec. Tratamiento i-shield, repele el agua, el aceite y protege al calzado de las manchas. 200 gramos de Tinsulate. Material sintético que retiene el calor dentro de la bota. Plantilla recambiable Ortholite. Entresuela de EVA moldeada. Suela Vibram. ',
        'category_id'=> 1,
        'created_at' => date("Y-m-d H:i:s"),
        'updated_at' => date("Y-m-d H:i:s")],
        ['title'=> 'WATERDOG TA450D',
        'pricing'=> 18.20,
        'short_description'=> 'Botella Termica Deportiva Waterdog 450 Cc Cantimplora Termo',
        'long_description'=> 'Construida con dos paredes de Acero Inoxidable que generan un aislamiento al vacío para lograr mantener el agua fría o caliente por más tiempo. Botella fácil de llenar y de poner hielo gracias a su boca ancha. Posee filtro de Té o Café que se puede utilizar de forma directa. La tapa posee correa para un fácil transporte. Aprobados por INTI e INAL (no tóxicos). 100% acero inoxidable. Fácil de llenar, gracias a su boca ancha. Se abre y se cierra presionando a rosca. Incluye filtro para té o café que se puede emplear colocándolo en forma directa. Compacto por fuera, con una gran capacidad interior. Capacidad: 450 cc. ',
        'category_id'=> 4,
        'created_at' => date("Y-m-d H:i:s"),
        'updated_at' => date("Y-m-d H:i:s")],
        ['title'=> 'Hi-Tec Tortola Escape',
        'pricing'=> 52.00,
        'short_description'=> 'Sandalia multideporte desarrollada para brindar frescura y comodidad en la temporada estival.',
        'long_description'=>'Un concepto hibrido que auna elementos tecnicos del calzado outdoor y el diseño funcional de las sandalias para adaptarse perfectamente a escenarios en la naturaleza o la ciudad. Los agujeros de ventilacion y drenaje en el corte, asi como los materiales empleados en su fabricacion mantienen el pie muy ventilado, favoreciendo la transpiracion. El confort tambien esta garantizado por la suavidad que aporta el forro interior de neopreno que evita roces y ampollas. Además, esta sandalia es fácil de calzar y de ajustar al pie por su sistema de lazado simple. Su lengüeta acolchada y los refuerzos de caucho en puntera y talón protegen de lesiones que pueden dificultar nuestra marcha. La plantilla extraíble aporta comodidad al andar y la suela de caucho carbono permite el uso regular de este modelo por terrenos de fácil recorrido. Corte de nobuck sintético Forro de neopreno Sistema de lazado con cordón elástico ',
        'category_id'=> 1,
        'created_at' => date("Y-m-d H:i:s"),
        'updated_at' => date("Y-m-d H:i:s")]
        ]);

    }
}
